### PR TITLE
Fix namespaces to allow use with Composer 2.x

### PR DESCRIPTION
**Pull request by mpowell-atomic**
Hi! Because of the warnings I was getting in Composer about the psr-4 autoloading standard
```
Class GTCrais\ApplicationLogParser\Parsers\WordPress\LogBodyParsers\BaseBodyParser located in ./vendor/gtcrais/application-log-parser/src/Parsers/WordPress/LogBodyParser/BaseBodyParser.php does not comply with psr-4 autoloading standard. Skipping.
Class GTCrais\ApplicationLogParser\Parsers\WordPress\LogBodyParsers\DefaultLogTypeBodyParser located in ./vendor/gtcrais/application-log-parser/src/Parsers/WordPress/LogBodyParser/DefaultLogTypeBodyParser.php does not comply with psr-4 autoloading standard. Skipping.
Class GTCrais\ApplicationLogParser\Parsers\WordPress\LogBodyParsers\LogTypeOneBodyParser located in ./vendor/gtcrais/application-log-parser/src/Parsers/WordPress/LogBodyParser/LogTypeOneBodyParser.php does not comply with psr-4 autoloading standard. Skipping.
```
 I have updated the three instances of a namespace typo. 

Thanks for this package!

### CODE REVIEW

**Comment by GTCrais** [comment]
Hey, thanks for the PR. It's actually the folder name that's wrong, and not the namespace of the classes. If you look at `ApplicationLogParser/src/Parsers/Laravel` you'll see that the folder within it is `LogBodyParsers`. Can you update your PR and switch it around - revert the class namespace, and change the folder name from `LogBodyParser` to `LogBodyParsers`?

**Comment by mpowell-atomic** [comment]
Ah. Ok! Sorry. Will update now. Thanks!

**Comment by mpowell-atomic** [comment]
@GTCrais Think this is better now. Appreciate the fast response and appreciate the package. Thanks!

**Comment by GTCrais** [comment]
Np. Merged and new version (v1.1.2) released. I had no idea someone was actually using this package :D

**Pull request merged**
